version: "3.9"

services:
  java-api:
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "8338:8338"
    container_name: CrudDemo
    expose:
      - "8338"
    links:
      - mongo
    depends_on:
      - mongo
  mongo:
    image: mongo
    ports:
      - "27017:27017"
    container_name: mongo